core/urls.py
from django.contrib import admin
from django.urls import path, include
from books.views import *
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('books.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models

from django.contrib.auth.models import User
# Create your models here.

class Book(models.Model):
    title = models.CharField(
        max_length=200,
        default="",
        null=True,
        blank=True,
    )
    author = models.CharField(
        max_length=200,
        default="",
        null=True,
        blank=True,
    )
    image = models.ImageField(null=True, blank=True,upload_to="images/books")
    content = models.TextField()
    def __str__(self):
        return f" {self.author} - {self.title} "
    @property
    def photo_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url

STATUS = (
     ('kutuphane','Kütüphanem'),
)
STATUS2 = (
    ('bitenler', 'Bitenler'),
    ('okunacaklar', 'Okunacaklar'),
    ('simdi_okuduklarım', 'Şimdi Okuduklarım'),
)
DEFAULT_STATUS = "kutuphane"
class BookUserList(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )
    booksList = models.ForeignKey(
        Book,
        on_delete=models.SET_NULL,
        null=True,
    )
    status = models.CharField(
        default=DEFAULT_STATUS,
        choices=STATUS,
        max_length=10
    )
    status2 = models.CharField(
        choices=STATUS2,
        max_length=30,
    )

class BookNotes(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
    )

    booksList = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
    )
    notes = models.TextField()

    timestamp = models.DateTimeField(auto_now_add=True)

templates/library/add-note.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'home/navbar.html' %}
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 login-box"  style="margin-top: 13%;">         
                    <h1 style="font-family:'Oswald', sans-serif; font-size: 40px !important;">{{book.title}} Kitabı için Not Ekleyin</h1>
                   <form action="{%  url 'add_note' book.id   %}" method="POST" name="notes">
                    {% csrf_token %}
                    <div class="textbox">
                        <textarea type="text" placeholder="Notunuz : " rows="8" cols="25" required id="id_notes" name="notes"></textarea>
                    </div>
                    
                    <button type="submit" class="btn">Not Ekle</button>

                   </form>
                </div>                                                            
            </div>                                    
    </div>

    {% endblock %}

templates/library/book-note-content.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'home/navbar.html' %}

        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
              <div class="col-lg-12 col-sm-12 col-xs-12">
                
                <h1 style="font-family:'Oswald', sans-serif; font-size: 40px !important; text-align: center;">Notlarınız</h1>
              
                {% for n in note %}
                <div class="tweet">
                    <div class="tweet--user">
                        <div class="tweet--user-name"><h5 style="font-family: 'Oswald', sans-serif; font-weight: bolder;">{{n.booksList.title}}</h5></div>
                      </div>
                    <p class="tweet--body">{{n.notes}}</p>
                    
                    <div class="tweet--time" style="font-weight: bolder; letter-spacing: 1px;">{{n.timestamp}}</div>
                </div>
                {% endfor %}
              
               </div>
            </div>                                                                                              
      </div>
        
{% endblock %}

templates/library/books-that-i-already-read.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'home/navbar.html' %}

        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
              <div class="col-lg-12" style="margin-bottom: 20%;">
                <div class="containerr">
                  <form action="/book-search-i-read/" method="post">
                    {% csrf_token %}
                     <input type="search" name="search_query" id="search_query" placeholder="Kitap Araması...">
                 </form>
                  <div class="search"></div>
                </div>
              </div>
              <div class="col-lg-12 col-sm-12 col-xs-12">
                <hr>
                <h1>BİTENLER</h1>
                <hr>
                {% for book in my_books %}
                <div class="card card--small">
                  <a href="{% url 'list_notes' book.booksList.id %}"></a><div class="card__image" style="background-image: url('{{book.booksList.photo_url|default_if_none:'#' }}')"></div></a>
               
                  <a href="{% url 'list_notes' book.booksList.id %}"><h2 class="card__title">{{book.booksList.title}}</h2></a>
                  <span class="card__subtitle">{{book.booksList.author}}</span>
                  <div class="card__action-bar">
                    <h4 style="float: right; color: rebeccapurple; font-family: 'Oswald', sans-serif;">Tebrikler</h4>
                    <!--<button class="card__button">Okuyacaklarıma <i class="fas fa-plus"></i></button>-->
                  </div>
                </div>
                {% endfor %}  
               </div>
            </div>                                                                                              
      </div>
      {% endblock %}

templates/library/books-that-i-read-now.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'home/navbar.html' %}

        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
              <div class="col-lg-12" style="margin-bottom: 20%;">
                <div class="containerr">
                  <form action="/book-search-i-am-reading/" method="post">
                    {% csrf_token %}
                     <input type="search" name="search_query" id="search_query" placeholder="Kitap Araması...">
                 </form>
                  <div class="search"></div>
                </div>
              </div>
              <div class="col-lg-12 col-sm-12 col-xs-12">
                <hr>
                <h1>ŞU ANDA OKUDUKLARIM</h1>
                <hr>
                {% for book in my_books %}
                <div class="card card--small">
                  <a href="{% url 'list_notes' book.booksList.id %}"><div class="card__image" style="background-image:  url('{{book.booksList.photo_url|default_if_none:'#' }}')"></div></a>
               
                  <a href="{% url 'list_notes' book.booksList.id %}"><h2 class="card__title">{{book.booksList.title}}</h2></a>
                  <span class="card__subtitle">{{book.booksList.author}}<a href="{% url 'create_note' book.booksList.id  %}" style="float:right; color: rebeccapurple;">Not ekle <i class="fas fa-plus"></i></a></span> 
                  <div class="card__action-bar">
                    <a class="card__button" id="book{{book.pk}}" data-bitenid="{{ book.pk }}">Bitenlere <i class="fas fa-check"></i></a>
                    <!--<button class="card__button">Okuyacaklarıma <i class="fas fa-plus"></i></button>-->
                  </div>
                </div>
                {% endfor %}  
            
               </div>
            </div>                                                                                              
      </div>
        
{% endblock %}

templates/library/books-that-ill-read.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'home/navbar.html' %}
        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
              <div class="col-lg-12" style="margin-bottom: 20%;">
                <div class="containerr">
                  <form action="/book-search-i-ll-read/" method="post">
                    {% csrf_token %}
                     <input type="search" name="search_query" id="search_query" placeholder="Kitap Araması...">
                 </form>
                  <div class="search"></div>
                </div>
              </div>
              <div class="col-lg-12 col-sm-12 col-xs-12">
                <hr>
                <h1>OKUNACAK KİTAPLAR</h1>
                <hr>
              {% for book in my_books %}
              <div class="card card--small">
                <a href="{% url 'list_notes' book.booksList.id %}"><div class="card__image" style="background-image:  url('{{book.booksList.photo_url|default_if_none:'#' }}')"></div></a>
               
                  <a href="{% url 'list_notes' book.booksList.id %}"><h2 class="card__title">{{book.booksList.title}}</h2></a>
                  <span class="card__subtitle">By {{book.booksList.author}} </span> 
                  
                <div class="card__action-bar">
                  <a class="card__button" id="book{{book.pk}}" data-simdiid="{{ book.pk }}">Şu an okunan <i class="fas fa-book"></i><i class="fas fa-plus"></i></a>
                  <!--<button class="card__button">Okuyacaklarıma <i class="fas fa-plus"></i></button>-->
                </div>
                
              </div>
              {% endfor %}
               </div>
            </div>                                                                                              
      </div>
        
      {% endblock %}

templates/library/my-library.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'home/navbar.html' %}
        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
              {% include 'user/user-card.html' %}
              <div class="col-lg-12" style="margin-bottom: 20%;">
                <div class="containerr">
                  <form action="/personal-book-search/" method="post">
                    {% csrf_token %}
                     <input type="search" name="search_query" id="search_query" placeholder="Kitap Araması...">
                 </form>
                  <div class="search"></div>
                </div>
              </div>
              <div class="col-lg-12 col-sm-12 col-xs-12" >
                <hr>
                <h1 id="demo">KÜTÜPHANEM</h1>
                <hr>
                {% for book in my_books %}
                <div class="card card--small">
                  <div class="card__image" style="background-image: url('{{book.booksList.photo_url|default_if_none:'#' }}')" data-toggle="modal" data-target="#modal{{ book.booksList.id }}" ></div>
               
                  <a href="{% url 'list_notes' book.booksList.id %}"><h2 class="card__title">{{book.booksList.title}}</h2></a>
                  <span class="card__subtitle">By {{book.booksList.author}} <a href="{% url 'create_note' book.booksList.id  %}" style="float:right; color: rebeccapurple;">Not ekle <i class="fas fa-plus"></i></a></span> 
                  
                  <div class="card__action-bar">
                    <a class="card__button" id="book{{book.pk}}" data-bitenid="{{ book.pk }}" ><i class="fas fa-check"></i></a>
                  
                    <a class="card__button" id="book{{book.pk}}" data-simdiid="{{ book.pk }}">Şu an <i class="fas fa-book"></i></a>

                    <a class="card__button" id="book{{book.pk}}" data-okunacakid="{{ book.pk }}">Okunacak <i class="fas fa-plus"></i></a>
                    
                   
                  </div>
                </div>
                <div class="modal fade" id="modal{{ book.booksList.id }}" style="top: 10%;"  tabindex="-1" role="dialog" aria-hidden="true">
                  <div  class="modal-dialog modal-dialog-scrollable">
                    <div class="modal-content">
                    
                      <!-- Modal Header -->
                      <div class="modal-header">
                        <h1 class="modal-title">{{book.booksList.title}} <small>{{book.booksList.author}}</small> </h1>
                        <button type="button" class="close" data-dismiss="modal">×</button>
                      </div>
                      
                      <!-- Modal body -->
                      <div class="modal-body">
                        <p>{{book.booksList.content}}</p>
                      
                      </div>
                      
                    
                    </div>
                  </div>
                </div>
                {% endfor %}
  
                 <center>
                  <nav aria-label="Page navigation example">
                    {% if my_books.has_other_pages %}
                    <ul class="pagination">
                      {% if my_books.has_previous %}
                      <li class="page-item"><a class="page-link" href="?page={{ my_books.previous_page_number }}" aria-label="Previous">&laquo;</a></li>
                     
                      {% endif %}
                      {% for i in my_books.paginator.page_range %}
                        {% if my_books.number == i %}
                          <li class="page-item active"><a class="page-link" >{{ i }} <span class="sr-only">(current)</span></a></span></li>
                        {% else %}
                          <li><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                        {% endif %}
                      {% endfor %}
                      {% if my_books.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ my_books.next_page_number }}">&raquo;</a></li>
                      {% endif %}
                    </ul>
                  {% endif %}
                  </nav>
                 </center>
      
               </div>
            </div>                                                                                              
      </div>
      <!-- <script>
        var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
            $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
            $('.loading').hide();
            }
            
        });


      </script> -->
 
      {% endblock %}

templates/library/now-book-note-content.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include 'home/navbar.html' %}

        <div class="container" style="margin-top: 20%;">
                 
            <div class="row align-items-center">
               <!-- <div class="col-lg-12">
                  <h1>Kitabınızın yüzde kaçı kaldı?</h1>
                  <svg id="animated" viewbox="0 0 100 100">
                    <circle cx="50" cy="50" r="45" fill="#FDB900"/>
                    <path id="progress" stroke-linecap="round" stroke-width="5" stroke="#fff" fill="none"
                          d="M50 10
                             a 40 40 0 0 1 0 80
                             a 40 40 0 0 1 0 -80">
                    </path>
                    <text id="count" x="50" y="50" text-anchor="middle" dy="7" font-size="20">?%</text>
                  </svg>
                  <label for="okunan" style="font-weight : bolder; font-size: 16px;">Kitap sayfa sayısını girin</label>
                  <input type="number" id="kitap" name="kitap" class="textbox">
                  <br>
                  <label for="okunan" style="font-weight : bolder; font-size: 16px;">Okuduğunuz sayfa sayısını girin</label>
                  <input type="text" id="okunan" class="textbox">
                  <button type="submit" id="hesap" class="btn">Hesapla</button>
                </div>
           -->
                <div class="col-lg-12 col-sm-12 col-xs-12">

                  <h1 style="font-family:'Oswald', sans-serif; font-size: 40px !important; text-align: center;">Notlarınız</h1>
                
                  {% for n in note %}
                  <div class="tweet">
                      <div class="tweet--user">
                          <div class="tweet--user-name"><h5 style="font-family: 'Oswald', sans-serif; font-weight: bolder;">{{n.booksList.title}}</h5></div>
                        </div>
                      <p class="tweet--body">{{n.notes}}</p>
                      
                      <div class="tweet--time" style="font-weight: bolder; letter-spacing: 1px;">{{n.timestamp}}</div>
                  </div>
                  {% endfor %}
                 
                 </div>
               
            </div>                                                                                              
      </div>
       
{% endblock %}